//------------
//System Values
//------------
var STAGE_WIDTH = 600,
	STAGE_HEIGHT = 400,
	TIME_PER_FRAME = 100,
	GAME_FONTS = "bold 20px sans-serif";

var PATH_CHAR = "img/spritesheet.png";

var CHAR_WIDTH = 72,
	CHAR_HEIGHT = 96,
	CHAR_START_X = 200,
	CHAR_START_Y = 200,
	CHAR_SPEED = 5,
	IMAGE_START_X = 0,
	IMAGE_START_NORTH_Y = 0,
	IMAGE_START_EAST_Y = 96,
	IMAGE_START_SOUTH_Y = 192,
	IMAGE_START_WEST_Y = 288,	
	SPRITE_WIDTH = 216;

var TEXT_PRELOADING = "Loading ...", 
	TEXT_PRELOADING_X = 200, 
	TEXT_PRELOADING_Y = 200;
	
	
var CONST = {

	// DIRECTIONAL STRINGS
	RIGHT: 'RIGHT',
	LEFT: 'LEFT',
	DOWN: 'DOWN',
	UP: 'UP',

	// Arrow Keys Codes By Character
	ARROW_RIGHT: 39,
	ARROW_DOWN: 40,
	ARROW_LEFT: 37,
	ARROW_UP: 38,

	// Default values
	DEFAULT_FRAME_RATE: 100,
	STAGE_HEIGHT: 400,
	STAGE_WIDTH: 600,

	TEXT_PRELOADING: 'Loading...',
	TEXT_PRELOADING_X: 200,
	TEXT_PRELOADING_Y: 200

};